// Dictionary of words
// array[0] == Present tense
// array[1] == Past tense
// array[2] == Past participle
var irregularVerbs = [
    [/ arises?[ .]/g, " arose ", " arisen "],
    [/ awakes?[ .]/g, " awoke ", " awoken "],
    [/ bears?[ .]/g, " bore ", " borne "],
    [/ beats?[ .]/g, " beat ", " beaten "],
    [/ becomes?[ .]/g, " became ", " become "],
    [/ begins?[ .]/g, " began ", " begun "],
    [/ bends?[ .]/g, " bent ", " bent "],
    [/ besets?[ .]/g, " beset ", " beset "],
    [/ bets?[ .]/g, " betted ", " bet "],
    [/ bids?[ .]/g, " bid ", " bid "],
    [/ binds?[ .]/g, " bound ", " bound "],
    [/ bites?[ .]/g, " bit ", " bitten "],
    [/ bleeds?[ .]/g, " bled ", " bled "],
    [/ blows?[ .]/g, " blew ", " blown "],
    [/ breaks?[ .]/g, " broke ", " broken "],
    [/ breeds?[ .]/g, " bred ", " bred "],
    [/ brings?[ .]/g, " brought ", " brought "],
    [/ broadcasts?[ .]/g, " broadcast ", " broadcast "],
    [/ builds?[ .]/g, " built ", " built "],
    [/ burns?[ .]/g, " burned ", " burnt "],
    [/ bursts?[ .]/g, " burst ", " burst "],
    [/ buys?[ .]/g, " bought ", " bought "],
    [/ casts?[ .]/g, " cast ", " cast "],
    [/ catche?s?[ .]/g, " caught ", " caught "],
    [/ chooses?[ .]/g, " chose ", " chosen "],
    [/ clings?[ .]/g, " clung ", " clung "],
    [/ comes?[ .]/g, " came ", " come "],
    [/ costs?[ .]/g, " cost ", " cost "],
    [/ creeps?[ .]/g, " crept ", " crept "],
    [/ cuts?[ .]/g, " cut ", " cut "],
    [/ deals?[ .]/g, " dealt ", " dealt "],
    [/ digs?[ .]/g, " dug ", " dug "],
    [/ dives?[ .]/g, " dove ", " dived "],
    [/ doe?s?[ .]/g, " did ", " done "],
    [/ draws?[ .]/g, " drew ", " drawn "],
    [/ dreams?[ .]/g, " dreamed ", " dreamt "],
    [/ drinks?[ .]/g, " drank ", " drunk "],
    [/ drives?[ .]/g, " drove ", " driven "],
    [/ eats?[ .]/g, " ate ", " eaten "],
    [/ falls?[ .]/g, " fell ", " fallen "],
    [/ feeds?[ .]/g, " fed ", " fed "],
    [/ feels?[ .]/g, " felt ", " felt "],
    [/ fights?[ .]/g, " fought ", " fought "],
    [/ finds?[ .]/g, " found ", " found "],
    [/ fits?[ .]/g, " fit ", " fit "],
    [/ flees?[ .]/g, " fled ", " fled "],
    [/ flings?[ .]/g, " flung ", " flung "],
    [/ flys?[ .]/g, " flew ", " flown "],
    [/ forbids?[ .]/g, " forbade ", " forbidden "],
    [/ forgets?[ .]/g, " forgot ", " forgotten "],
    [/ foregoe?s?[ .]/g, " forewent ", " foregone "],
    [/ forgives?[ .]/g, " forgave ", " forgiven "],
    [/ forsakes?[ .]/g, " forsook ", " forsaken "],
    [/ foretells?[ .]/g, " foretold ", " foretold "],
    [/ freezes?[ .]/g, " froze ", " frozen "],
    [/ gets?[ .]/g, " got ", " gotten "],
    [/ gives?[ .]/g, " gave ", " given "],
    [/ goe?s?[ .]/g, " went ", " gone "],
    [/ grinds?[ .]/g, " ground ", " ground "],
    [/ grows?[ .]/g, " grew ", " grown "],
    [/ hangs?[ .]/g, " hung ", " hung "],
    [/ haves?[ .]/g, " had ", " had "],
    [/ hears?[ .]/g, " heard ", " heard "],
    [/ hides?[ .]/g, " hid ", " hidden "],
    [/ hits?[ .]/g, " hit ", " hit "],
    [/ holds?[ .]/g, " held ", " held "],
    [/ hurts?[ .]/g, " hurt ", " hurt "],
    [/ keeps?[ .]/g, " kept ", " kept "],
    [/ kneels?[ .]/g, " knelt ", " knelt "],
    [/ knows?[ .]/g, " knew ", " known "],
    [/ lays?[ .]/g, " laid ", " laid "],
    [/ leads?[ .]/g, " led ", " led "],
    [/ leans?[ .]/g, " leaned ", " leaned "],
    [/ leaps?[ .]/g, " leaped ", " leapt "],
    [/ learns?[ .]/g, " learned ", " learned "],
    [/ leaves?[ .]/g, " left ", " left "],
    [/ lends?[ .]/g, " lent ", " lent "],
    [/ lets?[ .]/g, " let ", " let "],
    [/ lies?[ .]/g, " lay ", " lain "],
    [/ lights?[ .]/g, " lit ", " lighted "],
    [/ loses?[ .]/g, " lost ", " lost "],
    [/ makes?[ .]/g, " made ", " made "],
    [/ means?[ .]/g, " meant ", " meant "],
    [/ meets?[ .]/g, " met ", " met "],
    [/ misspells?[ .]/g, " misspelled ", " misspelled "],
    [/ mistakes?[ .]/g, " mistook ", " mistaken "],
    [/ mows?[ .]/g, " mowed ", " mowed "],
    [/ overcomes?[ .]/g, " overcame ", " overcome "],
    [/ overdoe?s?[ .]/g, " overdid ", " overdone "],
    [/ overtakes?[ .]/g, " overtook ", " overtaken "],
    [/ overthrows?[ .]/g, " overthrew ", " overthrown "],
    [/ pays?[ .]/g, " paid ", " paid "],
    [/ pleads?[ .]/g, " pleaded ", " plead "],
    [/ proves?[ .]/g, " proved ", " proven "],
    [/ puts?[ .]/g, " put ", " put "],
    [/ quits?[ .]/g, " quit ", " quit "],
    [/ reads?[ .]/g, " read ", " read "],
    [/ rids?[ .]/g, " rid ", " rid "],
    [/ rides?[ .]/g, " rode ", " ridden "],
    [/ rings?[ .]/g, " rang ", " rung "],
    [/ rises?[ .]/g, " rose ", " risen "],
    [/ runs?[ .]/g, " ran ", " run "],
    [/ saws?[ .]/g, " sawed ", " sawed "],
    [/ says?[ .]/g, " said ", " said "],
    [/ sees?[ .]/g, " saw ", " seen "],
    [/ seeks?[ .]/g, " sought ", " sought "],
    [/ sells?[ .]/g, " sold ", " sold "],
    [/ sends?[ .]/g, " sent ", " sent "],
    [/ sets?[ .]/g, " set ", " set "],
    [/ sews?[ .]/g, " sewed ", " sewn "],
    [/ shakes?[ .]/g, " shook ", " shaken "],
    [/ shears?[ .]/g, " sheared ", " sheared "],
    [/ sheds?[ .]/g, " shed ", " shed "],
    [/ shines?[ .]/g, " shone ", " shone "],
    [/ shoots?[ .]/g, " shot ", " shot "],
    [/ shows?[ .]/g, " showed ", " shown "],
    [/ shrinks?[ .]/g, " shrank ", " shrunk "],
    [/ shuts?[ .]/g, " shut ", " shut "],
    [/ sings?[ .]/g, " sang ", " sung "],
    [/ sinks?[ .]/g, " sank ", " sunk "],
    [/ sits?[ .]/g, " sat ", " sat "],
    [/ sleeps?[ .]/g, " slept ", " slept "],
    [/ slays?[ .]/g, " slew ", " slayed "],
    [/ slides?[ .]/g, " slid ", " slid "],
    [/ slings?[ .]/g, " slung ", " slung "],
    [/ slits?[ .]/g, " slit ", " slit "],
    [/ smells?[ .]/g, " smelled ", " smelled "],
    [/ smites?[ .]/g, " smote ", " smitten "],
    [/ sows?[ .]/g, " sowed ", " sowed "],
    [/ speaks?[ .]/g, " spoke ", " spoken "],
    [/ speeds?[ .]/g, " speeded ", " speeded "],
    [/ spells?[ .]/g, " spelled ", " spelled "],
    [/ spends?[ .]/g, " spent ", " spent "],
    [/ spills?[ .]/g, " spilled ", " spilled "],
    [/ spins?[ .]/g, " spun ", " spun "],
    [/ spits?[ .]/g, " spat ", " spat "],
    [/ splits?[ .]/g, " split ", " split "],
    [/ spoils?[ .]/g, " spoiled ", " spoiled "],
    [/ spreads?[ .]/g, " spread ", " spread "],
    [/ springs?[ .]/g, " sprang ", " sprung "],
    [/ stands?[ .]/g, " stood ", " stood "],
    [/ steals?[ .]/g, " stole ", " stolen "],
    [/ sticks?[ .]/g, " stuck ", " stuck "],
    [/ stings?[ .]/g, " stung ", " stung "],
    [/ stinks?[ .]/g, " stank ", " stunk "],
    [/ strides?[ .]/g, " strode ", " stridden "],
    [/ strikes?[ .]/g, " struck ", " struck "],
    [/ strives?[ .]/g, " strove ", " striven "],
    [/ swears?[ .]/g, " swore ", " sworn "],
    [/ sweeps?[ .]/g, " swept ", " swept "],
    [/ swells?[ .]/g, " swelled ", " swelled "],
    [/ swims?[ .]/g, " swam ", " swum "],
    [/ swings?[ .]/g, " swung ", " swung "],
    [/ takes?[ .]/g, " took ", " taken "],
    [/ teache?s?[ .]/g, " taught ", " taught "],
    [/ tears?[ .]/g, " tore ", " torn "],
    [/ tells?[ .]/g, " told ", " told "],
    [/ thinks?[ .]/g, " thought ", " thought "],
    [/ thrives?[ .]/g, " thrived ", " thrived "],
    [/ throws?[ .]/g, " threw ", " thrown "],
    [/ thrusts?[ .]/g, " thrust ", " thrust "],
    [/ treads?[ .]/g, " trod ", " trodden "],
    [/ understands?[ .]/g, " understood ", " understood "],
    [/ upholds?[ .]/g, " upheld ", " upheld "],
    [/ upsets?[ .]/g, " upset ", " upset "],
    [/ wakes?[ .]/g, " woke ", " woken "],
    [/ wears?[ .]/g, " wore ", " worn "],
    [/ weaves?[ .]/g, " wove ", " woven "],
    [/ weds?[ .]/g, " wed ", " wed "],
    [/ weeps?[ .]/g, " wept ", " wept "],
    [/ wins?[ .]/g, " won ", " won "],
    [/ winds?[ .]/g, " wound ", " wound "],
    [/ withdraws?[ .]/g, " withdrew ", " withdrawn "],
    [/ withholds?[ .]/g, " withheld ", " withheld "],
    [/ withstands?[ .]/g, " withstood ", " withstood "],
    [/ wrings?[ .]/g, " wrung ", " wrung "],
    [/ writes?[ .]/g, " wrote ", " written "],
];

var linkingVerbs = [
    [/ am[ .]/g, " was "],
    [/ appear?s[ .]/g, " appeared "],
    [/ are[ .]/g, " were "],
    [/ look?s[ .]/g, " looked "],
    [/ seem?s[ .]/g, " seemed "],
    [/ sound?s[ .]/g, " sounded "],
    [/ taste?s[ .]/g, " tasted "],
];

var modalVerbs = [
    [/ can't be[ .]/g, " couldn't have been "],
    [/ couldn't be[ .]/g, " couldn't have been "],
    [/ may not be[ .]/g, " may not have been "],
    [/ might not be[ .]/g, " might not have been "],
    [/ must not be[ .]/g, " must not have been "],
    [/ shall not be[ .]/g, " shouldn't have been "],
    [/ shouldn't be[ .]/g, " shouldn't have been "],
    [/ won't be[ .]/g, " wouldn't have been "],
    [/ wouldn't be[ .]/g, " wouldn't have been "],

    [/ can be[ .]/g, " could have been "],
    [/ could be[ .]/g, " could have been "],
    [/ may be[ .]/g, " may have been "],
    [/ might be[ .]/g, " might have been "],
    [/ must be[ .]/g, " must have been "],
    [/ shall be[ .]/g, " should have been "],
    [/ should be[ .]/g, " should have been "],
    [/ will be[ .]/g, " would have been "],
    [/ would be[ .]/g, " would have been "],

    [/ can't[ .]/g, " couldn't have "],
    [/ couldn't[ .]/g, " couldn't have "],
    [/ may not[ .]/g, " may not have "],
    [/ might not[ .]/g, " might not have "],
    [/ must not[ .]/g, " must not have "],
    [/ shall not[ .]/g, " shouldn't have "],
    [/ shouldn't[ .]/g, " shouldn't have "],
    [/ will not[ .]/g, " wouldn't have "],
    [/ wouldn't[ .]/g, " wouldn't have "],

    [/ can[ .]/g, " could have "],
    [/ could[ .]/g, " could have "],
    [/ may[ .]/g, " may have "],
    [/ might[ .]/g, " might have "],
    [/ must[ .]/g, " must have "],
    [/ shall[ .]/g, " should have "],
    [/ should[ .]/g, " should have "],
    [/ will[ .]/g, " would have "],
    [/ would[ .]/g, " would have "],
];

var regularVerbs = [
    [/ inherit[ .]/g, "inherited"],
    [/ visit[ .]/g, "visited"],
];

// Converts string to past tense
// The method should be executed using a string variable - the method does not accept arguments
String.prototype.toPastTense = function () {
    var text = this;
    irregularVerbs.forEach(function (element) {
        text = text.replace(element[0], element[1]);
    });
    return text;
};

// Converts string to present tense
// The method should be executed using a string variable - the method does not accept arguments
String.prototype.toPastParticiple = function () {
    // Not implemented
};

// Test
var testText = "Here is my short story with present, present perfect, and present continuous tense. Would you please check my story and point out my mistakes. Thank you for being helpful to me. It is 9:00 A.M. in the morning and the first thing I am going to do is to knock on my door of my mother’s room. She always sleeps till late. Today, she shouldn’t sleep much as a special guest is coming to meet us in the evening and for she must get up. I normally wake-up at 7:00 A.M and then watch the morning show. After it I take shower and eat my breakfast. I don’t like eating omelets in the breakfast, I prefer taking two slices of Dawn bread, one glass of milk, and one table spoon of peanut instead. It keeps me healthy, active, and smart. My sister has been sitting at the table for fifteen and waiting for me to make her breakfast, but I can’t do it. I am not in the mood of doing anything for her. My sister has never prepared breakfast for herself; and I do not like it. She must know her responsibility and stop being dependent on me, because she is growing up now and she needs to learn how to do small things like this.";
console.log(testText.toPastTense());
